name: ci
on:
  push:
  pull_request:

jobs:
  windows_x86_64:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Build
        run: |
          cmake -B build
          cmake --build build

  linux_x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install Cmake & Make
      run: |
        sudo apt-get install cmake make

    - name: Build
      run: |
          cmake -B build
          cmake --build build

  master:
    needs: [linux_x86_64, windows_x86_64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
